### ISSUE TITLE
Can you explain how you got the list of coinjoin txs?

### ISSUE THREAD

**Issue by MatteoRomiti** [jgmontoya/wasabi-cj-stats#1]
I'd be happy to help you with improving your dataset, if possible.

**Comment by jgmontoya** [comment]
I got them from @nopara73's repo, here: https://github.com/nopara73/WasabiVsSamourai/blob/master/WasabiVsSamourai/WasabiCoinJoins.txt

**Comment by MatteoRomiti** [comment]
Thanks, I was exactly looking at the same repo. Quite cool!

**Comment by nopara73** [comment]
There's a more complete list here: https://github.com/nopara73/WasabiCjEfficiency/blob/master/WasabiCjEfficiency/CoinJoinsMain.txt

The repository mentioned above only examines the coinjoins from the time when Samourai started operating.

**Comment by MatteoRomiti** [comment]
Thanks. From what I understood, though, this is what you are using

https://github.com/nopara73/WasabiVsSamourai/blob/master/WasabiVsSamourai/CoinJoinIndexer.cs#L99

right? Or there is something else?

**Comment by nopara73** [comment]
That's all. It's not complex :)
